# 项目配置文件

data:
  raw_data_dir: data/raw/
  processed_data_dir: data/processed/
  # PHM2010 数据集或其他数据集路径
  dataset_path: data/raw/PHM_2010/

preprocessing:
  # 去噪方法, 平滑窗口大小等参数
  denoising_method: 'wavelet' # 'moving_average', 'wavelet', etc.
  smoothing_window: 5

feature_extraction:
  time_domain_features: ['mean', 'std', 'rms', 'skewness', 'kurtosis', 'peak', 'crest_factor']
  frequency_domain_features: ['main_frequency_amplitude', 'energy_ratio'] # 基于 FFT
  wavelet_packet:
    level: 4 # 小波包分解层数

feature_selection:
  spearman_threshold: 0.8
  pearson_threshold: 0.8
  n_features_to_select: 12 # 最终筛选出的特征数量 (10-15)

dimensionality_reduction:
  pca_n_components: 0.90 # 保留 90% 的方差或指定主成分数量

models:
  random_forest:
    n_estimators: 100
    max_depth: 15
    min_samples_split: 2
    min_samples_leaf: 1
    bootstrap: true
    random_state: 42
    model_path: "results/random_forest_model.pkl"
    
  bpnn:
    input_size: 4  # 特征数量，由PCA结果决定
    hidden_layers: [128, 64]  # 贝叶斯优化得到的最佳结构
    output_size: 1
    learning_rate: 0.014672  # 贝叶斯优化得到的最佳学习率
    weight_decay: 0.0001  # 贝叶斯优化得到的最佳权重衰减
    activation: 'relu'  # 贝叶斯优化得到的最佳激活函数
    output_activation: 'linear'
    dropout_rate: 0.0  # 贝叶斯优化得到的最佳dropout率
    epochs: 5000
    batch_size: 8  # 贝叶斯优化得到的最佳批量大小
    use_lr_scheduler: false
    train_function: 'adam'  # 支持'adam', 'sgd', 'rmsprop', 'trainlm'
    lm_damping: 0.1
    early_stopping_patience: 50
    min_error: 0.00001
    l1_weight: 0.0
    # 学习率调度器配置

training:
  test_size: 0.2
  cv_folds: 5 # 交叉验证折数
  random_state: 42
  model_type: 'bpnn'  # 指定模型类型为BPNN
  train_experiments: ['c1', 'c4']  # 用于训练的实验
  test_experiments: ['c6']  # 用于测试的实验
  evaluation_metrics: ['mae', 'rmse', 'r2']
  target_metrics:
    mae_threshold: 5.0
    rmse_threshold: 5.0
    r2_threshold: 0.85

tuning:
  bayesian_optimization_iterations: 50  # 贝叶斯优化迭代次数
  optimization_metric: 'mae'  # 优化的指标
  bpnn:
    learning_rate_range: [0.0001, 0.05]
    weight_decay_range: [0.0001, 0.01]
    dropout_rate_range: [0.0, 0.5]
    batch_size_options: [8, 16, 32, 64]
    activation_options: ['relu', 'tanh', 'leaky_relu']
    hidden_layers_options: [[16], [32], [64], [32, 16], [64, 32], [128, 64], [64, 32, 16], [32, 16, 8]]

logging:
  log_file: 'project.log'
  log_level: 'INFO' 