# 项目配置文件

data:
  raw_data_dir: data/raw/
  processed_data_dir: data/processed/
  # PHM2010 数据集或其他数据集路径
  dataset_path: data/raw/PHM_2010/

preprocessing:
  # 去噪方法, 平滑窗口大小等参数
  denoising_method: 'wavelet' # 'moving_average', 'wavelet', etc.
  smoothing_window: 5

feature_extraction:
  time_domain_features: ['mean', 'std', 'rms', 'skewness', 'kurtosis', 'peak', 'crest_factor']
  frequency_domain_features: ['main_frequency_amplitude', 'energy_ratio'] # 基于 FFT
  wavelet_packet:
    level: 4 # 小波包分解层数

feature_selection:
  spearman_threshold: 0.8
  pearson_threshold: 0.8
  n_features_to_select: 12 # 最终筛选出的特征数量 (10-15)

dimensionality_reduction:
  pca_n_components: 0.90 # 保留 90% 的方差或指定主成分数量

models:
  random_forest:
    n_estimators_range: [30, 150]
    max_depth_range: [3, 8]
    # 其他 RF 参数
  bpnn:
    hidden_layer_sizes: [100, 50] # 示例隐藏层结构
    activation: 'relu'
    optimizer: 'adam'
    learning_rate_range: [0.0001, 0.01]
    epochs: 100
    batch_size: 32
    early_stopping_patience: 10
  fusion:
    # 融合策略参数 (例如线性回归的权重)
    pass

training:
  test_size: 0.2
  cv_folds: 5 # 交叉验证折数
  random_state: 42
  evaluation_metrics: ['mae', 'rmse', 'r2']
  target_metrics:
    mae_threshold: 5.0
    rmse_threshold: 5.0
    r2_threshold: 0.85

tuning:
  bayesian_optimization_iterations: 50 # 贝叶斯优化迭代次数

logging:
  log_file: 'project.log'
  log_level: 'INFO' 