# 随机森林优化配置文件

data:
  raw_data_dir: data/raw/
  processed_data_dir: data/processed/
  dataset_path: data/raw/PHM_2010/

preprocessing:
  denoising_method: 'wavelet'
  smoothing_window: 5
  standardization: true  # 标准化处理
  outlier_removal:
    method: 'iqr'
    factor: 1.5

feature_extraction:
  time_domain_features: ['mean', 'std', 'rms', 'skewness', 'kurtosis', 'peak', 'crest_factor', 'variance', 'min', 'max', 'median', 'range']
  frequency_domain_features: ['main_frequency_amplitude', 'energy_ratio', 'spectral_entropy', 'spectral_centroid', 'dominant_frequency']
  wavelet_packet:
    level: 5  # 增加小波包分解层数
  statistical_features: true  # 添加统计特征
  interaction_features: true  # 添加交互特征

feature_selection:
  spearman_threshold: 0.6   # 降低相关性阈值，保留更多特征
  pearson_threshold: 0.6
  n_features_to_select: 20  # 增加特征数量
  importance_threshold: 0.01  # 特征重要性阈值
  use_rfe: true  # 使用递归特征消除
  mutual_info: true  # 使用互信息选择特征

dimensionality_reduction:
  pca_n_components: 0.98    # 保留更多方差
  use_pca: false  # 关闭PCA，仅使用特征选择

models:
  random_forest:
    # 调整参数减少过拟合
    n_estimators: 500      # 增加树的数量，但控制复杂度
    max_depth: 10          # 减小树的深度，限制过拟合
    min_samples_split: 8   # 增加分裂所需最小样本数
    min_samples_leaf: 4    # 增加叶节点最小样本数
    bootstrap: true
    max_features: 'log2'   # 减少每次分裂考虑的特征数
    criterion: 'squared_error'
    random_state: 42
    max_samples: 0.7       # 减少每棵树使用的样本比例，增加随机性
    oob_score: true
    warm_start: false
    ccp_alpha: 0.01        # 添加成本复杂度剪枝参数，控制过拟合

  # 集成模型配置，同样调整基础模型参数
  ensemble:
    enabled: true
    method: 'stacking'
    base_models:
      # 调整基础模型参数以减少过拟合
      - type: 'random_forest'
        n_estimators: 500
        max_depth: 10
        min_samples_split: 8
        min_samples_leaf: 4
        max_features: 'log2'
        max_samples: 0.7
        ccp_alpha: 0.01
      - type: 'random_forest'
        n_estimators: 700
        max_depth: 8
        min_samples_split: 10
        min_samples_leaf: 5
        max_features: 'log2'
        max_samples: 0.6
        ccp_alpha: 0.015
      - type: 'random_forest'
        n_estimators: 400
        max_depth: 12
        min_samples_split: 6
        min_samples_leaf: 3
        max_features: 0.5
        max_samples: 0.8
        ccp_alpha: 0.008
      # 保留XGBoost模拟模型但调整参数
      - type: 'random_forest'
        n_estimators: 500
        max_depth: 6       # 更小的深度
        bootstrap: false
        min_samples_leaf: 6
        max_features: 0.7
        ccp_alpha: 0.02
    meta_model: 'ridge'    # 使用带正则化的ridge回归作为元模型

# 网格搜索参数设置（禁用）
grid_search:
  enabled: false
  param_grid:
    n_estimators: [100, 300, 500, 700, 1000]
    max_depth: [10, 15, 20, 25, 30, None]
    min_samples_split: [2, 3, 5, 10]
    min_samples_leaf: [1, 2, 4, 8]
    max_features: ['sqrt', 'log2', 0.33, 0.5]
    bootstrap: [true]
    criterion: ['squared_error', 'absolute_error', 'friedman_mse']
  scoring: 'neg_mean_absolute_error'
  cv_folds: 5
  n_jobs: -1

training:
  test_size: 0.2
  cv_folds: 5             # 交叉验证折数
  random_state: 42
  model_type: 'random_forest'
  train_experiments: ['c1', 'c4']
  test_experiments: ['c6']
  evaluation_metrics: ['mae', 'rmse', 'r2']
  target_metrics:
    mae_threshold: 5.0
    rmse_threshold: 5.0
    r2_threshold: 0.85
  early_stopping: false

logging:
  log_file: 'project.log'
  log_level: 'INFO' 