# 随机森林优化配置文件 - 平衡泛化版本

data:
  raw_data_dir: data/raw/
  processed_data_dir: data/processed/
  dataset_path: data/raw/PHM_2010/

preprocessing:
  denoising_method: 'wavelet'
  smoothing_window: 5
  standardization: true  # 标准化处理
  outlier_removal:
    method: 'zscore'  # 使用Z-score
    factor: 2.8       # 平衡Z-score阈值

feature_extraction:
  time_domain_features: ['mean', 'std', 'rms', 'skewness', 'kurtosis', 'peak', 'crest_factor', 'variance', 'min', 'max', 'median', 'range']
  frequency_domain_features: ['main_frequency_amplitude', 'energy_ratio', 'spectral_entropy', 'spectral_centroid', 'dominant_frequency']
  wavelet_packet:
    level: 3  # 保持降低的小波包分解层数
  statistical_features: true  # 添加统计特征
  interaction_features: true  # 恢复交互特征，但后续会更严格地筛选

feature_selection:
  spearman_threshold: 0.75    # 平衡相关性阈值
  pearson_threshold: 0.8     # 平衡相关性阈值
  n_features_to_select: 10    # 适中特征数量
  importance_threshold: 0.03  # 平衡特征重要性阈值
  use_rfe: true  # 使用递归特征消除
  mutual_info: true  # 使用互信息选择特征

dimensionality_reduction:
  pca_n_components: 0.95    # 保持适度方差保留
  use_pca: false  # 保持关闭PCA

models:
  random_forest:
    # 平衡参数设置
    n_estimators: 700      # 适中树数量
    max_depth: 8           # 适中树深度
    min_samples_split: 10  # 适中分裂样本数
    min_samples_leaf: 6    # 适中叶节点样本数
    bootstrap: true
    max_features: 0.6      # 平衡特征比例
    criterion: 'squared_error'
    random_state: 42
    max_samples: 0.7       # 平衡样本比例
    oob_score: true
    warm_start: false
    ccp_alpha: 0.02        # 平衡剪枝强度

  # 平衡集成模型配置
  ensemble:
    enabled: true
    method: 'stacking'     # 恢复使用stacking
    base_models:
      # 基础模型1：变体1
      - type: 'random_forest'
        n_estimators: 600
        max_depth: 7
        min_samples_split: 12
        min_samples_leaf: 5
        max_features: 0.6
        max_samples: 0.7
        ccp_alpha: 0.02
      # 基础模型2：变体2
      - type: 'random_forest'
        n_estimators: 800
        max_depth: 6
        min_samples_split: 10
        min_samples_leaf: 4
        max_features: 'sqrt'
        max_samples: 0.65
        ccp_alpha: 0.015
      # 基础模型3：变体3
      - type: 'random_forest'
        n_estimators: 500
        max_depth: 9
        min_samples_split: 8
        min_samples_leaf: 3
        max_features: 0.7
        max_samples: 0.75
        ccp_alpha: 0.01
    meta_model: 'ridge'    # 保持使用Ridge回归作为元模型

# 网格搜索参数设置（禁用）
grid_search:
  enabled: false
  param_grid:
    n_estimators: [100, 300, 500, 700, 1000]
    max_depth: [10, 15, 20, 25, 30, None]
    min_samples_split: [2, 3, 5, 10]
    min_samples_leaf: [1, 2, 4, 8]
    max_features: ['sqrt', 'log2', 0.33, 0.5]
    bootstrap: [true]
    criterion: ['squared_error', 'absolute_error', 'friedman_mse']
  scoring: 'neg_mean_absolute_error'
  cv_folds: 5
  n_jobs: -1

training:
  test_size: 0.2
  cv_folds: 5             # 交叉验证折数
  random_state: 42
  model_type: 'random_forest'
  train_experiments: ['c1', 'c4']
  test_experiments: ['c6']
  evaluation_metrics: ['mae', 'rmse', 'r2']
  target_metrics:
    mae_threshold: 5.0
    rmse_threshold: 5.0
    r2_threshold: 0.85
  early_stopping: false

logging:
  log_file: 'project.log'
  log_level: 'INFO' 