data:
  dataset_path: data/raw/PHM_2010/
  processed_data_dir: data/processed/
  raw_data_dir: data/raw/
dimensionality_reduction:
  pca_n_components: 0.95
feature_extraction:
  frequency_domain_features:
  - main_frequency_amplitude
  - energy_ratio
  - spectral_entropy
  - spectral_centroid
  - spectral_kurtosis
  - freq_band_energy_ratio_low
  - freq_band_energy_ratio_mid
  - freq_band_energy_ratio_high
  time_domain_features:
  - mean
  - std
  - rms
  - skewness
  - kurtosis
  - peak
  - crest_factor
  - form_factor
  - impulse_factor
  - clearance_factor
  - shape_factor
  - peak_to_peak
  wavelet_packet:
    level: 4
    wavelet_type: db4
feature_selection:
  n_features_to_select: 15
  pearson_threshold: 0.85
  spearman_threshold: 0.75
logging:
  log_file: project.log
  log_level: INFO
models:
  bpnn:
    activation: tanh
    batch_size: 16
    dropout_rate: 0.0
    early_stopping_patience: 50
    epochs: 5000
    hidden_layers:
    - 32
    - 16
    - 8
    input_size: 4
    l1_weight: 0.0
    learning_rate: 0.01
    lm_damping: 0.1
    min_error: 1.0e-05
    output_activation: linear
    output_size: 1
    train_function: adam
    use_lr_scheduler: false
    weight_decay: 0.001
  random_forest:
    bootstrap: true
    max_depth: 15
    min_samples_leaf: 1
    min_samples_split: 2
    model_path: results/random_forest_model.pkl
    n_estimators: 100
    random_state: 42
preprocessing:
  denoising_method: wavelet
  iqr_factor: 1.5
  outlier_method: zscore
  smoothing_window: 5
  wavelet_type: db4
  zscore_threshold: 3.0
training:
  cv_folds: 5
  evaluation_metrics:
  - mae
  - rmse
  - r2
  model_type: bpnn
  random_state: 42
  target_metrics:
    mae_threshold: 5.0
    r2_threshold: 0.85
    rmse_threshold: 5.0
  test_size: 0.2
tuning:
  bayesian_optimization_iterations: 50
  bpnn:
    activation_options:
    - tanh
    - relu
    - leaky_relu
    batch_size_options:
    - 16
    - 32
    - 64
    dropout_rate_range:
    - 0.1
    - 0.5
    hidden_layers_options:
    - - 32
      - 16
    - - 64
      - 32
    - - 128
      - 64
    - - 64
      - 32
      - 16
    - - 128
      - 64
      - 32
    learning_rate_range:
    - 0.001
    - 0.01
    weight_decay_range:
    - 0.0001
    - 0.01
  optimization_metric: mae
  random_forest:
    criterion_options:
    - absolute_error
    - squared_error
    - friedman_mse
    - poisson
    max_depth_range:
    - 5
    - 30
    max_features_options:
    - sqrt
    - log2
    - 0.5
    - 0.7
    min_samples_leaf_range:
    - 1
    - 5
    min_samples_split_range:
    - 2
    - 10
    n_estimators_range:
    - 100
    - 500
